AWSTemplateFormatVersion: "2010-09-09"

Resources:

  CodeDeployerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "CodeDeployerRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal:
              Service:
                - "codedeploy.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole

  
